### PR TITLE
Travis ci

### PR DESCRIPTION
**Pull request by Bagaric**
Added Travis config + Solium for solidity linting

### CODE REVIEW

**Comment by kosecki123** [comment]
Please take a look at Travis errors, make sure build and tests passing.

**Comment by Bagaric** [comment]
Managed to get travis building. Still seems that 2 tests are failing.
Maybe a separate branch and PR for fixing those tests.

**Comment by kosecki123** [comment]
You are using testrpc as eth simulator, this tool is now continued as ganache-cli, https://github.com/trufflesuite/ganache-cli/releases/tag/v6.0.3 Please switch to the lastest stable release of ganache-cli

**Comment by Bagaric** [comment]
@kosecki123 please review and merge.

**Pull request merged**
